# CONFIGURACIÓN DE ALEMBIC
# Este archivo le dice a Alembic dónde están los scripts y cómo conectarse.

[alembic]
# Carpeta donde se guardan las migraciones
script_location = alembic

# Cómo se llamarán los archivos (Año_Mes_Día-ID-Nombre)
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d_%%(minute).2d-%%(rev)s_%%(slug)s

# URL de ejemplo (env.py la pisa con la real del .env por seguridad)
sqlalchemy.url = postgresql://user:pass@localhost/dbname

# --- GESTIÓN DE LOGS (Consola) ---

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

# Nivel de detalle: WARN (solo errores), INFO (mensajes útiles)
[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

# Handler: Indica que los mensajes salgan por la terminal
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

# Formatter: Define la estética (Hora - Nivel - Quién envía - Mensaje)
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
